Footer: added copy for CC license
mozilla/network-pulse pull request #1431
Opened 2020-10-07 11:33 UTC by Yashs911

Related issue: #1379 
Summary: 
- [x] Removed "License" copy
- [x] Organized items by alphabetical order (except for "Donate", which should remain the first link)
- [x] Added "Most content available under a Creative Commons license." Link for Creative Commons license is here
- [ ] Changed Mozilla logo to the most updated one. Logo here
- [x] Change copy to be consistent with other web properties: "Join our Mozilla News email list to take action and stay updated!"

If you don't know who to ask for a review, try @pomax , @cadecairos , or @mmmavis. If you do, please delete this line.

2020-10-07 16:17 UTC, mmmavis commented
Thanks @Yashs911 ! I will review this once you have access to the new logo & have this PR updated!

2020-10-07 18:49 UTC, Yashs911 commented
Hi, @mmmavis PR updated

2020-10-07 23:18 UTC, mmmavis requested changes
Few requests!

2020-10-07 23:18 UTC, mmmavis commented on components/footer/footer.jsx
> +                    src="../assets/svg/mozilla-block-white.8a5ea59a8186.svg"
please rename the image to `mozilla-block-white.svg` and this line can stay unchanged

2020-10-07 23:18 UTC, mmmavis commented on components/footer/footer.jsx
> +                    style={{ width: 96, height: 31 }}
```suggestion
                    width="96"
```

2020-10-07 23:18 UTC, mmmavis commented on components/footer/footer.jsx
> +                    .Most content available under a{" "}
```suggestion
                    . Most content available under a{" "}
```

2020-10-07 23:18 UTC, mmmavis commented on components/newsletter-sign-up/newsletter-sign-up.jsx
> +  ctaDescription: `Join our Mozilla News email list to take action and stay updated!`,
I would change line 137-141 to 
```jsx
<div
  dangerouslySetInnerHTML={{
    __html: this.props.ctaDescription,
  }}
/>
```
and this line to
```suggestion
  ctaDescription: `<p>Join our <b>Mozilla News</b> email list to take action and stay updated!</p>`,
```

2020-10-08 03:53 UTC, Yashs911 commented
@mmmavis Have made the changes as requested

2020-10-16 20:56 UTC, mmmavis approved these changes
✨

2020-10-16 20:56 UTC, merged